site_name: Hyperledger技术博客
site_url: https://wutongtree.github.io/hyperledger/
theme: simplex
site_description: '介绍Hyperledger技术的博客'

docs_dir: markdowns
site_dir: docs

pages:
- 首页: index.md
- 源码分析: 
  - Hyperledger源码分析: technology/index.md
  - 共识算法: technology/consensus.md
- 安装部署: installation/index.md
- 原创翻译: translations/index.md
- 行业动态: news/index.md

- 网络资源: resources/index.md
 
markdown_extensions:
  - extra
  - tables
  - toc
  - fenced_code
  - smarty
  - mdx_math:
      enable_dollar_delimiter: True
  - footnotes

copyright: Copyright &copy; 2014-2016 <a href="https://wutongtree.com" target="_blank">wutongtree.com</a>
